version: "3.5"
services:
  druid-router:
    image: mpolatcan/druid:0.20.0-java8
    hostname: druid
    environment:
      DRUID_SERVICES: |
        router
      DRUID_REQUEST_LOGGING_TYPE: "file"
      DRUID_REQUEST_LOGGING_DIR: "/home/druid/log"
    ports:
      - 8888:8888