config_loader_sh_template: |
  #!/usr/bin/env bash
  function load_config() {{
      if [[ "$2" != "NULL" ]]; then
          printf "$1=$2\n" >> "${{DRUID_CONF_DIR}}/$3"
      fi
  }}

  function load_config_with_opt() {{
      if [[ "$2" != "NULL" ]]
          then
              printf "$1=$3\n" >> "${{DRUID_CONF_DIR}}/$5"
      else
          printf "$1=$4\n" >> "${{DRUID_CONF_DIR}}/$5"
      fi
  }}

  # Create configuration directories
  mkdir -p ${{DRUID_CONF_DIR}}/{{_common,broker,coordinator,historical,middlemanager,overlord,router}}

  # Copy default log4j2.xml configuration to _common/log4j2.xml
  cat <<EOF > ${{DRUID_CONF_DIR}}/_common/log4j2.xml
  <?xml version="1.0" encoding="UTF-8" ?>
  <Configuration status="WARN">
    <Appenders>
      <Console name="Console" target="SYSTEM_OUT">
        <PatternLayout pattern="%d{{ISO8601}} %p [%t] %c - %m%n"/>
      </Console>
    </Appenders>
    <Loggers>
      <Root level="info">
        <AppenderRef ref="Console"/>
      </Root>

      <!-- Uncomment to enable logging of all HTTP requests
      <Logger name="org.apache.druid.jetty.RequestLog" additivity="false" level="DEBUG">
          <AppenderRef ref="Console"/>
      </Logger>
      -->
    </Loggers>
  </Configuration>
  EOF

  # Load JVM configurations of each Druid service
  DRUID_SERVICES=(broker coordinator historical middlemanager overlord router)
  for DRUID_SERVICE in ${{DRUID_SERVICES[@]}}; do
      ENV_VAR_PREFIX=$(echo $DRUID_SERVICE | tr '[a-z]' '[A-Z]')

      ENV_VAR_JVM_HEAP_SIZE="${{ENV_VAR_PREFIX}}_JVM_HEAP_SIZE"
      ENV_VAR_JVM_MAX_HEAP_SIZE="${{ENV_VAR_PREFIX}}_JVM_MAX_HEAP_SIZE"
      ENV_VAR_JVM_MAX_DIRECT_MEMORY_SIZE="${{ENV_VAR_PREFIX}}_JVM_MAX_DIRECT_MEMORY_SIZE"

      echo "org.apache.druid.cli.Main server ${{DRUID_SERVICE}}" >> ${{DRUID_CONF_DIR}}/$DRUID_SERVICE/main.config

  cat <<EOF > ${{DRUID_CONF_DIR}}/$DRUID_SERVICE/jvm.config
  -server
  -Xms${{!ENV_VAR_JVM_HEAP_SIZE:=512m}}
  -Xmx${{!ENV_VAR_JVM_MAX_HEAP_SIZE:=2g}}
  -XX:MaxDirectMemorySize=${{!ENV_VAR_JVM_MAX_DIRECT_MEMORY_SIZE:=3g}}
  -XX:+ExitOnOutOfMemoryError
  -Duser.timezone=UTC
  -Dfile.encoding=UTF-8
  -Djava.io.tmpdir=var/tmp
  -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
  EOF
  done

  {load_fn_calls}

config_files:
  - path: druid_configs/common.yaml
    filename: _common/common.runtime.properties
  - path: druid_configs/broker.yaml
    filename: broker/runtime.properties
  - path: druid_configs/coordinator.yaml
    filename: coordinator/runtime.properties
  - path: druid_configs/historical.yaml
    filename: historical/runtime.properties
  - path: druid_configs/middlemanager.yaml
    filename: middlemanager/runtime.properties
  - path: druid_configs/overlord.yaml
    filename: overlord/runtime.properties
output_dir: ../../base