#!/usr/bin/env bash
function load_config() {
    if [[ "$2" != "NULL" ]]; then
        printf "$1=$2\n" >> "${DRUID_CONF_DIR}/$3"
    fi
}

function load_config_with_opt() {
    if [[ "$2" != "NULL" ]]
        then
            printf "$1=$3\n" >> "${DRUID_CONF_DIR}/$5"
    else
        printf "$1=$4\n" >> "${DRUID_CONF_DIR}/$5"
    fi
}

# Create configuration directories
mkdir -p ${DRUID_CONF_DIR}/{_common,broker,coordinator,historical,middleManager,overlord,router}

# Copy default log4j2.xml configuration to _common/log4j2.xml
cat <<EOF > ${DRUID_CONF_DIR}/_common/log4j2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Configuration status="WARN">
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <PatternLayout pattern="%d{ISO8601} %p [%t] %c - %m%n"/>
    </Console>
  </Appenders>
  <Loggers>
    <Root level="info">
      <AppenderRef ref="Console"/>
    </Root>

    <!-- Uncomment to enable logging of all HTTP requests
    <Logger name="org.apache.druid.jetty.RequestLog" additivity="false" level="DEBUG">
        <AppenderRef ref="Console"/>
    </Logger>
    -->
  </Loggers>
</Configuration>
EOF

# Load JVM configurations of each Druid service
DRUID_SERVICES=(broker coordinator historical middleManager overlord router)
for DRUID_SERVICE in ${DRUID_SERVICES[@]}; do
    ENV_VAR_PREFIX=$(echo $DRUID_SERVICE | tr '[a-z]' '[A-Z]')

    ENV_VAR_JVM_HEAP_SIZE="${ENV_VAR_PREFIX}_JVM_HEAP_SIZE"
    ENV_VAR_JVM_MAX_HEAP_SIZE="${ENV_VAR_PREFIX}_JVM_MAX_HEAP_SIZE"
    ENV_VAR_JVM_MAX_DIRECT_MEMORY_SIZE="${ENV_VAR_PREFIX}_JVM_MAX_DIRECT_MEMORY_SIZE"

    echo "org.apache.druid.cli.Main server ${DRUID_SERVICE}" >> ${DRUID_CONF_DIR}/$DRUID_SERVICE/main.config

cat <<EOF > ${DRUID_CONF_DIR}/$DRUID_SERVICE/jvm.config
-server
-Xms${!ENV_VAR_JVM_HEAP_SIZE:=512m}
-Xmx${!ENV_VAR_JVM_MAX_HEAP_SIZE:=2g}
-XX:MaxDirectMemorySize=${!ENV_VAR_JVM_MAX_DIRECT_MEMORY_SIZE:=3g}
-XX:+ExitOnOutOfMemoryError
-Duser.timezone=UTC
-Dfile.encoding=UTF-8
-Djava.io.tmpdir=var/tmp
-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
EOF
done

load_config "druid.extensions.directory" "${DRUID_HOME}/extensions" "_common/common.runtime.properties"
load_config "druid.extensions.hadoopDependenciesDir" "${DRUID_HOME}/hadoop-dependencies" "_common/common.runtime.properties"
load_config "druid.extensions.loadList" "${DRUID_EXTENSIONS_LOADLIST:=NULL}" "_common/common.runtime.properties"
load_config "druid.extensions.searchCurrentClassloader" "${DRUID_EXTENSIONS_SEARCHCURRENTCLASSLOADER:=true}" "_common/common.runtime.properties"
load_config "druid.extensions.useExtensionClassloaderFirst" "${DRUID_EXTENSIONS_USEEXTENSIONCLASSLOADERFIRST:=false}" "_common/common.runtime.properties"
load_config "druid.extensions.hadoopContainerDruidClasspath" "${DRUID_EXTENSIONS_HADOOPCONTAINERDRUIDCLASSPATH:=NULL}" "_common/common.runtime.properties"
load_config "druid.extensions.addExtensionsToHadoopContainer" "${DRUID_EXTENSIONS_ADDEXTENSIONSTOHADOOPCONTAINER:=false}" "_common/common.runtime.properties"
load_config "druid.modules.excludeList" "${DRUID_MODULES_EXCLUDELIST:=[]}" "_common/common.runtime.properties"
load_config "druid.zk.paths.base" "${DRUID_ZK_PATHS_BASE:=/druid}" "_common/common.runtime.properties"
load_config "druid.zk.paths.propertiesPath" "${DRUID_ZK_PATHS_BASE}/properties" "_common/common.runtime.properties"
load_config "druid.zk.paths.announcementsPath" "${DRUID_ZK_PATHS_BASE}/announcements" "_common/common.runtime.properties"
load_config "druid.zk.paths.liveSegmentsPath" "${DRUID_ZK_PATHS_BASE}/segments" "_common/common.runtime.properties"
load_config "druid.zk.paths.loadQueuePath" "${DRUID_ZK_PATHS_BASE}/loadQueue" "_common/common.runtime.properties"
load_config "druid.zk.paths.coordinatorPath" "${DRUID_ZK_PATHS_BASE}/coordinator" "_common/common.runtime.properties"
load_config "druid.zk.paths.servedSegmentsPath" "${DRUID_ZK_PATHS_BASE}/servedSegments" "_common/common.runtime.properties"
load_config "druid.zk.paths.indexer.base" "${DRUID_ZK_PATHS_BASE}/indexer" "_common/common.runtime.properties"
load_config "druid.zk.paths.indexer.announcementsPath" "${DRUID_ZK_PATHS_BASE}/indexer/announcements" "_common/common.runtime.properties"
load_config "druid.zk.paths.indexer.tasksPath" "${DRUID_ZK_PATHS_BASE}/indexer/tasks" "_common/common.runtime.properties"
load_config "druid.zk.paths.indexer.statusPath" "${DRUID_ZK_PATHS_BASE}/indexer/status" "_common/common.runtime.properties"
load_config "druid.zk.service.host" "${DRUID_ZK_SERVICE_HOST:=NULL}" "_common/common.runtime.properties"
load_config "druid.zk.service.user" "${DRUID_ZK_SERVICE_USER:=NULL}" "_common/common.runtime.properties"
load_config "druid.zk.service.pwd" "${DRUID_ZK_SERVICE_PWD:=NULL}" "_common/common.runtime.properties"
load_config "druid.zk.service.authScheme" "${DRUID_ZK_SERVICE_AUTHSCHEME:=digest}" "_common/common.runtime.properties"
load_config "druid.zk.service.sessionTimeoutMs" "${DRUID_ZK_SERVICE_SESSIONTIMEOUTMS:=30000}" "_common/common.runtime.properties"
load_config "druid.zk.service.connectionTimeoutMs" "${DRUID_ZK_SERVICE_CONNECTIONTIMEOUTMS:=15000}" "_common/common.runtime.properties"
load_config "druid.zk.service.compress" "${DRUID_ZK_SERVICE_COMPRESS:=true}" "_common/common.runtime.properties"
load_config "druid.zk.service.acl" "${DRUID_ZK_SERVICE_ACL:=false}" "_common/common.runtime.properties"
load_config "druid.discovery.curator.path" "${DRUID_DISCOVERY_CURATOR_PATH:=/druid/discovery}" "_common/common.runtime.properties"
load_config "druid.exhibitor.service.hosts" "${DRUID_EXHIBITOR_SERVICE_HOSTS:=NULL}" "_common/common.runtime.properties"
load_config "druid.exhibitor.service.port" "${DRUID_EXHIBITOR_SERVICE_PORT:=8080}" "_common/common.runtime.properties"
load_config "druid.exhibitor.service.restUriPath" "${DRUID_EXHIBITOR_SERVICE_RESTURIPATH:=/exhibitor/v1/cluster/list}" "_common/common.runtime.properties"
load_config "druid.exhibitor.service.useSsl" "${DRUID_EXHIBITOR_SERVICE_USESSL:=false}" "_common/common.runtime.properties"
load_config "druid.exhibitor.service.pollingMs" "${DRUID_EXHIBITOR_SERVICE_POLLINGMS:=10000}" "_common/common.runtime.properties"
load_config "druid.enablePlaintextPort" "${DRUID_ENABLEPLAINTEXTPORT:=true}" "_common/common.runtime.properties"
load_config "druid.enableTlsPort" "${DRUID_ENABLETLSPORT:=false}" "_common/common.runtime.properties"
load_config "druid.server.https.keyStorePath" "${DRUID_SERVER_HTTPS_KEYSTOREPATH:=NULL}" "_common/common.runtime.properties"
load_config "druid.server.https.keyStoreType" "${DRUID_SERVER_HTTPS_KEYSTORETYPE:=NULL}" "_common/common.runtime.properties"
load_config "druid.server.https.certAlias" "${DRUID_SERVER_HTTPS_CERTALIAS:=NULL}" "_common/common.runtime.properties"
load_config "druid.server.https.keyStorePassword" "${DRUID_SERVER_HTTPS_KEYSTOREPASSWORD:=NULL}" "_common/common.runtime.properties"
load_config "druid.server.https.keyManagerFactoryAlgorithm" "${DRUID_SERVER_HTTPS_KEYMANAGERFACTORYALGORITHM:=NULL}" "_common/common.runtime.properties"
load_config "druid.server.https.keyManagerPassword" "${DRUID_SERVER_HTTPS_KEYMANAGERPASSWORD:=NULL}" "_common/common.runtime.properties"
load_config "druid.server.https.includeCipherSuites" "${DRUID_SERVER_HTTPS_INCLUDECIPHERSUITES:=NULL}" "_common/common.runtime.properties"
load_config "druid.server.https.excludeCipherSuites" "${DRUID_SERVER_HTTPS_EXCLUDECIPHERSUITES:=NULL}" "_common/common.runtime.properties"
load_config "druid.server.https.includeProtocols" "${DRUID_SERVER_HTTPS_INCLUDEPROTOCOLS:=NULL}" "_common/common.runtime.properties"
load_config "druid.server.https.excludeProtocols" "${DRUID_SERVER_HTTPS_EXCLUDEPROTOCOLS:=NULL}" "_common/common.runtime.properties"
load_config "druid.client.https.protocol" "${DRUID_CLIENT_HTTPS_PROTOCOL:=TLSv1.2}" "_common/common.runtime.properties"
load_config "druid.client.https.trustStoreType" "${DRUID_CLIENT_HTTPS_TRUSTSTORETYPE:=NULL}" "_common/common.runtime.properties"
load_config "druid.client.https.trustStorePath" "${DRUID_CLIENT_HTTPS_TRUSTSTOREPATH:=NULL}" "_common/common.runtime.properties"
load_config "druid.client.https.trustStoreAlgorithm" "${DRUID_CLIENT_HTTPS_TRUSTSTOREALGORITHM:=NULL}" "_common/common.runtime.properties"
load_config "druid.client.https.trustStorePassword" "${DRUID_CLIENT_HTTPS_TRUSTSTOREPASSWORD:=NULL}" "_common/common.runtime.properties"
load_config "druid.auth.authenticatorChain" "${DRUID_AUTH_AUTHENTICATORCHAIN:=NULL}" "_common/common.runtime.properties"
load_config "druid.auth.authorizers" "${DRUID_AUTH_AUTHORIZERS:=NULL}" "_common/common.runtime.properties"
load_config "druid.auth.unsecuredPaths" "${DRUID_AUTH_UNSECUREDPATHS:=NULL}" "_common/common.runtime.properties"
load_config "druid.auth.allowUnauthenticatedHttpOptions" "${DRUID_AUTH_ALLOWUNAUTHENTICATEDHTTPOPTIONS:=false}" "_common/common.runtime.properties"
load_config "druid.escalator.type" "${DRUID_ESCALATOR_TYPE:=NULL}" "_common/common.runtime.properties"
load_config "druid.startup.logging.logProperties" "${DRUID_STARTUP_LOGGING_LOGPROPERTIES:=false}" "_common/common.runtime.properties"
load_config "druid.startup.logging.maskProperties" "${DRUID_STARTUP_LOGGING_MASKPROPERTIES:=NULL}" "_common/common.runtime.properties"
load_config "druid.request.logging.type" "${DRUID_REQUEST_LOGGING_TYPE:=file}" "_common/common.runtime.properties"
load_config "druid.request.logging.dir" "${DRUID_LOG_DIR}" "_common/common.runtime.properties"
load_config "druid.request.logging.filePattern" "${DRUID_REQUEST_LOGGING_FILEPATTERN:="yyyy-MM-dd'.log'"}" "_common/common.runtime.properties"
load_config "druid.request.logging.feed" "${DRUID_REQUEST_LOGGING_FEED:=NULL}" "_common/common.runtime.properties"
load_config "druid.request.logging.setMDC" "${DRUID_REQUEST_LOGGING_SETMDC:=false}" "_common/common.runtime.properties"
load_config "druid.request.logging.setContextMDC" "${DRUID_REQUEST_LOGGING_SETCONTEXTMDC:=False}" "_common/common.runtime.properties"
load_config "druid.request.logging.queryTimeThresholdMs" "${DRUID_REQUEST_LOGGING_QUERYTIMETHRESHOLDMS:=0}" "_common/common.runtime.properties"
load_config "druid.request.logging.sqlQueryTimeThresholdMs" "${DRUID_REQUEST_LOGGING_SQLQUERYTIMETHRESHOLDMS:=0}" "_common/common.runtime.properties"
load_config "druid.request.logging.mutedQueryTypes" "${DRUID_REQUEST_LOGGING_MUTEDQUERYTYPES:=[]}" "_common/common.runtime.properties"
load_config "druid.request.logging.delegate.type" "${DRUID_REQUEST_LOGGING_DELEGATE_TYPE:=NULL}" "_common/common.runtime.properties"
load_config "druid.request.logging.loggerProviders" "${DRUID_REQUEST_LOGGING_LOGGERPROVIDERS:=NULL}" "_common/common.runtime.properties"
load_config "druid.request.logging.nativeQueryLogger" "${DRUID_REQUEST_LOGGING_NATIVEQUERYLOGGER:=NULL}" "_common/common.runtime.properties"
load_config "druid.request.logging.sqlQueryLogger" "${DRUID_REQUEST_LOGGING_SQLQUERYLOGGER:=NULL}" "_common/common.runtime.properties"
load_config "druid.audit.manager.auditHistoryMillis" "${DRUID_AUDIT_MANAGER_AUDITHISTORYMILLIS:=NULL}" "_common/common.runtime.properties"
load_config "druid.audit.manager.includePayloadAsDimensionInMetric" "${DRUID_AUDIT_MANAGER_INCLUDEPAYLOADASDIMENSIONINMETRIC:=false}" "_common/common.runtime.properties"
load_config "druid.monitoring.emissionPeriod" "${DRUID_MONITORING_EMISSIONPERIOD:=NULL}" "_common/common.runtime.properties"
load_config "druid.monitoring.monitors" "${DRUID_MONITORING_MONITORS:=NULL}" "_common/common.runtime.properties"
load_config "druid.emitter" "${DRUID_EMITTER:=noop}" "_common/common.runtime.properties"
load_config "druid.emitter.logging.loggerClass" "${DRUID_EMITTER_LOGGING_LOGGERCLASS:=LoggingEmitter}" "_common/common.runtime.properties"
load_config "druid.emitter.logging.logLevel" "${DRUID_EMITTER_LOGGING_LOGLEVEL:=info}" "_common/common.runtime.properties"
load_config "druid.emitter.http.flushMillis" "${DRUID_EMITTER_HTTP_FLUSHMILLIS:=60000}" "_common/common.runtime.properties"
load_config "druid.emitter.http.flushCount" "${DRUID_EMITTER_HTTP_FLUSHCOUNT:=500}" "_common/common.runtime.properties"
load_config "druid.emitter.http.basicAuthentication" "${DRUID_EMITTER_HTTP_BASICAUTHENTICATION:=NULL}" "_common/common.runtime.properties"
load_config "druid.emitter.http.flushTimeout" "${DRUID_EMITTER_HTTP_FLUSHTIMEOUT:=NULL}" "_common/common.runtime.properties"
load_config "druid.emitter.http.batchingStrategy" "${DRUID_EMITTER_HTTP_BATCHINGSTRATEGY:=ARRAY}" "_common/common.runtime.properties"
load_config "druid.emitter.http.maxBatchSize" "${DRUID_EMITTER_HTTP_MAXBATCHSIZE:=NULL}" "_common/common.runtime.properties"
load_config "druid.emitter.http.batchQueueSizeLimit" "${DRUID_EMITTER_HTTP_BATCHQUEUESIZELIMIT:=NULL}" "_common/common.runtime.properties"
load_config "druid.emitter.http.minHttpTimeoutMillis" "${DRUID_EMITTER_HTTP_MINHTTPTIMEOUTMILLIS:=0}" "_common/common.runtime.properties"
load_config "druid.emitter.http.recipientBaseUrl" "${DRUID_EMITTER_HTTP_RECIPIENTBASEURL:=NULL}" "_common/common.runtime.properties"
load_config "druid.emitter.http.ssl.useDefaultJavaContext" "${DRUID_EMITTER_HTTP_SSL_USEDEFAULTJAVACONTEXT:=false}" "_common/common.runtime.properties"
load_config "druid.emitter.http.ssl.trustStorePath" "${DRUID_EMITTER_HTTP_SSL_TRUSTSTOREPATH:=NULL}" "_common/common.runtime.properties"
load_config "druid.emitter.http.ssl.trustStoreType" "${DRUID_EMITTER_HTTP_SSL_TRUSTSTORETYPE:=NULL}" "_common/common.runtime.properties"
load_config "druid.emitter.http.ssl.trustStoreAlgorithm" "${DRUID_EMITTER_HTTP_SSL_TRUSTSTOREALGORITHM:=NULL}" "_common/common.runtime.properties"
load_config "druid.emitter.http.ssl.trustStorePassword" "${DRUID_EMITTER_HTTP_SSL_TRUSTSTOREPASSWORD:=NULL}" "_common/common.runtime.properties"
load_config "druid.emitter.http.ssl.protocol" "${DRUID_EMITTER_HTTP_SSL_PROTOCOL:=TLSv1.2}" "_common/common.runtime.properties"
load_config "druid.emitter.http.parametrized.recipientBaseUrlPattern" "${DRUID_EMITTER_HTTP_PARAMETRIZED_RECIPIENTBASEURLPATTERN:=NULL}" "_common/common.runtime.properties"
load_config "druid.emitter.http.composing.emitters" "${DRUID_EMITTER_HTTP_COMPOSING_EMITTERS:=[]}" "_common/common.runtime.properties"
load_config "druid.metadata.storage.type" "${DRUID_METADATA_STORAGE_TYPE:=derby}" "_common/common.runtime.properties"
load_config "druid.metadata.storage.connector.connectURI" "${DRUID_METADATA_STORAGE_CONNECTOR_CONNECTURI:=NULL}" "_common/common.runtime.properties"
load_config "druid.metadata.storage.connector.user" "${DRUID_METADATA_STORAGE_CONNECTOR_USER:=NULL}" "_common/common.runtime.properties"
load_config "druid.metadata.storage.connector.password" "${DRUID_METADATA_STORAGE_CONNECTOR_PASSWORD:=NULL}" "_common/common.runtime.properties"
load_config "druid.metadata.storage.connector.createTables" "${DRUID_METADATA_STORAGE_CONNECTOR_CREATETABLES:=true}" "_common/common.runtime.properties"
load_config "druid.metadata.storage.tables.base" "${DRUID_METADATA_STORAGE_TABLES_BASE:=druid}" "_common/common.runtime.properties"
load_config "druid.metadata.storage.tables.dataSource" "${DRUID_METADATA_STORAGE_TABLES_DATASOURCE:=druid_dataSource}" "_common/common.runtime.properties"
load_config "druid.metadata.storage.tables.pendingSegments" "${DRUID_METADATA_STORAGE_TABLES_PENDINGSEGMENTS:=druid_pendingSegments}" "_common/common.runtime.properties"
load_config "druid.metadata.storage.tables.segments" "${DRUID_METADATA_STORAGE_TABLES_SEGMENTS:=druid_segments}" "_common/common.runtime.properties"
load_config "druid.metadata.storage.tables.rules" "${DRUID_METADATA_STORAGE_TABLES_RULES:=druid_rules}" "_common/common.runtime.properties"
load_config "druid.metadata.storage.tables.config" "${DRUID_METADATA_STORAGE_TABLES_CONFIG:=druid_config}" "_common/common.runtime.properties"
load_config "druid.metadata.storage.tables.tasks" "${DRUID_METADATA_STORAGE_TABLES_TASKS:=druid_tasks}" "_common/common.runtime.properties"
load_config "druid.metadata.storage.tables.taskLog" "${DRUID_METADATA_STORAGE_TABLES_TASKLOG:=druid_taskLog}" "_common/common.runtime.properties"
load_config "druid.metadata.storage.tables.taskLock" "${DRUID_METADATA_STORAGE_TABLES_TASKLOCK:=druid_taskLock}" "_common/common.runtime.properties"
load_config "druid.metadata.storage.tables.supervisors" "${DRUID_METADATA_STORAGE_TABLES_SUPERVISORS:=druid_supervisors}" "_common/common.runtime.properties"
load_config "druid.metadata.storage.tables.audit" "${DRUID_METADATA_STORAGE_TABLES_AUDIT:=druid_audit}" "_common/common.runtime.properties"
load_config "druid.storage.host" "${DRUID_STORAGE_HOST:=NULL}" "_common/common.runtime.properties"
load_config "druid.storage.keyspace" "${DRUID_STORAGE_KEYSPACE:=NULL}" "_common/common.runtime.properties"
load_config "druid.storage.type" "${DRUID_STORAGE_TYPE:=local}" "_common/common.runtime.properties"
load_config "druid.storage.storageDirectory" "${DRUID_STORAGE_STORAGEDIRECTORY:=/tmp/druid/localStorage}" "_common/common.runtime.properties"
load_config "druid.storage.bucket" "${DRUID_STORAGE_BUCKET:=NULL}" "_common/common.runtime.properties"
load_config "druid.storage.baseKey" "${DRUID_STORAGE_BASEKEY:=NULL}" "_common/common.runtime.properties"
load_config "druid.storage.disableAcl" "${DRUID_STORAGE_DISABLEACL:=false}" "_common/common.runtime.properties"
load_config "druid.storage.archiveBucket" "${DRUID_STORAGE_ARCHIVEBUCKET:=NULL}" "_common/common.runtime.properties"
load_config "druid.storage.archiveBaseKey" "${DRUID_STORAGE_ARCHIVEBASEKEY:=NULL}" "_common/common.runtime.properties"
load_config "druid.storage.sse.type" "${DRUID_STORAGE_SSE_TYPE:=NULL}" "_common/common.runtime.properties"
load_config "druid.storage.sse.kms.keyId" "${DRUID_STORAGE_SSE_KMS_KEYID:=NULL}" "_common/common.runtime.properties"
load_config "druid.storage.sse.custom.base64EncodedKey" "${DRUID_STORAGE_SSE_CUSTOM_BASE64ENCODEDKEY:=NULL}" "_common/common.runtime.properties"
load_config "druid.storage.useS3aSchema" "${DRUID_STORAGE_USES3ASCHEMA:=false}" "_common/common.runtime.properties"
load_config "druid.indexer.logs.type" "${DRUID_INDEXER_LOGS_TYPE:=file}" "_common/common.runtime.properties"
load_config "druid.indexer.logs.kill.enabled" "${DRUID_INDEXER_LOGS_KILL_ENABLED:=false}" "_common/common.runtime.properties"
load_config "druid.indexer.logs.kill.durationToRetain" "${DRUID_INDEXER_LOGS_KILL_DURATIONTORETAIN:=NULL}" "_common/common.runtime.properties"
load_config "druid.indexer.logs.kill.initialDelay" "${DRUID_INDEXER_LOGS_KILL_INITIALDELAY:=NULL}" "_common/common.runtime.properties"
load_config "druid.indexer.logs.kill.delay" "${DRUID_INDEXER_LOGS_KILL_DELAY:=NULL}" "_common/common.runtime.properties"
load_config "druid.indexer.logs.directory" "${DRUID_HOME}/log" "_common/common.runtime.properties"
load_config "druid.indexer.logs.s3Bucket" "${DRUID_INDEXER_LOGS_S3BUCKET:=NULL}" "_common/common.runtime.properties"
load_config "druid.indexer.logs.s3Prefix" "${DRUID_INDEXER_LOGS_S3PREFIX:=NULL}" "_common/common.runtime.properties"
load_config "druid.indexer.logs.disableAcl" "${DRUID_INDEXER_LOGS_DISABLEACL:=false}" "_common/common.runtime.properties"
load_config "druid.indexer.logs.container" "${DRUID_INDEXER_LOGS_CONTAINER:=NULL}" "_common/common.runtime.properties"
load_config "druid.indexer.logs.prefix" "${DRUID_INDEXER_LOGS_PREFIX:=NULL}" "_common/common.runtime.properties"
load_config "druid.indexer.logs.bucket" "${DRUID_INDEXER_LOGS_BUCKET:=NULL}" "_common/common.runtime.properties"
load_config "druid.selectors.indexing.serviceName" "${DRUID_SELECTORS_INDEXING_SERVICENAME:=druid/overlord}" "_common/common.runtime.properties"
load_config "druid.selectors.coordinator.serviceName" "${DRUID_SELECTORS_COORDINATOR_SERVICENAME:=druid/coordinator}" "_common/common.runtime.properties"
load_config "druid.announcer.segmentsPerNode" "${DRUID_ANNOUNCER_SEGMENTSPERNODE:=50}" "_common/common.runtime.properties"
load_config "druid.announcer.maxBytesPerNode" "${DRUID_ANNOUNCER_MAXBYTESPERNODE:=524288}" "_common/common.runtime.properties"
load_config "druid.announcer.skipDimensionsAndMetrics" "${DRUID_ANNOUNCER_SKIPDIMENSIONSANDMETRICS:=false}" "_common/common.runtime.properties"
load_config "druid.announcer.skipLoadSpec" "${DRUID_ANNOUNCER_SKIPLOADSPEC:=false}" "_common/common.runtime.properties"
load_config "druid.javascript.enabled" "${DRUID_JAVASCRIPT_ENABLED:=false}" "_common/common.runtime.properties"
load_config "druid.indexing.doubleStorage" "${DRUID_INDEXING_DOUBLESTORAGE:=double}" "_common/common.runtime.properties"
load_config "druid.generic.useDefaultValueForNull" "${DRUID_GENERIC_USEDEFAULTVALUEFORNULL:=true}" "_common/common.runtime.properties"
load_config "druid.global.http.numConnections" "${DRUID_GLOBAL_HTTP_NUMCONNECTIONS:=20}" "_common/common.runtime.properties"
load_config "druid.global.http.compressionCodec" "${DRUID_GLOBAL_HTTP_COMPRESSIONCODEC:=gzip}" "_common/common.runtime.properties"
load_config "druid.global.http.readTimeout" "${DRUID_GLOBAL_HTTP_READTIMEOUT:=PT15M}" "_common/common.runtime.properties"
load_config "druid.global.http.unusedConnectionTimeout" "${DRUID_GLOBAL_HTTP_UNUSEDCONNECTIONTIMEOUT:=PT4M}" "_common/common.runtime.properties"
load_config "druid.global.http.numMaxThreads" "${DRUID_GLOBAL_HTTP_NUMMAXTHREADS:=NULL}" "_common/common.runtime.properties"
load_config "druid.cache.type" "${DRUID_CACHE_TYPE:=caffeine}" "_common/common.runtime.properties"
load_config "druid.cache.sizeInBytes" "${DRUID_CACHE_SIZEINBYTES:=0}" "_common/common.runtime.properties"
load_config "druid.cache.initialSize" "${DRUID_CACHE_INITIALSIZE:=500000}" "_common/common.runtime.properties"
load_config "druid.cache.logEvictionCount" "${DRUID_CACHE_LOGEVICTIONCOUNT:=0}" "_common/common.runtime.properties"
load_config "druid.cache.expireAfter" "${DRUID_CACHE_EXPIREAFTER:=NULL}" "_common/common.runtime.properties"
load_config "druid.cache.cacheExecutorFactory" "${DRUID_CACHE_CACHEEXECUTORFACTORY:=COMMON_FJP}" "_common/common.runtime.properties"
load_config "druid.cache.evictOnClose" "${DRUID_CACHE_EVICTONCLOSE:=false}" "_common/common.runtime.properties"
load_config "druid.cache.expiration" "${DRUID_CACHE_EXPIRATION:=2592000}" "_common/common.runtime.properties"
load_config "druid.cache.timeout" "${DRUID_CACHE_TIMEOUT:=500}" "_common/common.runtime.properties"
load_config "druid.cache.hosts" "${DRUID_CACHE_HOSTS:=NULL}" "_common/common.runtime.properties"
load_config "druid.cache.maxObjectSize" "${DRUID_CACHE_MAXOBJECTSIZE:=52428800}" "_common/common.runtime.properties"
load_config "druid.cache.memcachedPrefix" "${DRUID_CACHE_MEMCACHEDPREFIX:=druid}" "_common/common.runtime.properties"
load_config "druid.cache.numConnections" "${DRUID_CACHE_NUMCONNECTIONS:=1}" "_common/common.runtime.properties"
load_config "druid.cache.protocol" "${DRUID_CACHE_PROTOCOL:=binary}" "_common/common.runtime.properties"
load_config "druid.cache.locator" "${DRUID_CACHE_LOCATOR:=consistent}" "_common/common.runtime.properties"
load_config "druid.query.topN.minTopNThreshold" "${DRUID_QUERY_TOPN_MINTOPNTHRESHOLD:=1000}" "_common/common.runtime.properties"
load_config "druid.query.search.maxSearchLimit" "${DRUID_QUERY_SEARCH_MAXSEARCHLIMIT:=1000}" "_common/common.runtime.properties"
load_config "druid.query.search.saerchStrategy" "${DRUID_QUERY_SEARCH_SAERCHSTRATEGY:=useIndexes}" "_common/common.runtime.properties"
load_config "druid.query.segmentMetadata.defaultHistory" "${DRUID_QUERY_SEGMENTMETADATA_DEFAULTHISTORY:=P1W}" "_common/common.runtime.properties"
load_config "druid.query.segmentMetadata.defaultAnalysisTypes" "${DRUID_QUERY_SEGMENTMETADATA_DEFAULTANALYSISTYPES:=NULL}" "_common/common.runtime.properties"
load_config "druid.query.groupBy.maxMergingDictionarySize" "${DRUID_QUERY_GROUPBY_MAXMERGINGDICTIONARYSIZE:=100000000}" "_common/common.runtime.properties"
load_config "druid.query.groupBy.maxOnDiskStorage" "${DRUID_QUERY_GROUPBY_MAXONDISKSTORAGE:=0}" "_common/common.runtime.properties"
load_config "druid.query.groupBy.defaultStrategy" "${DRUID_QUERY_GROUPBY_DEFAULTSTRATEGY:=v2}" "_common/common.runtime.properties"
load_config "druid.query.groupBy.singleThreaded" "${DRUID_QUERY_GROUPBY_SINGLETHREADED:=false}" "_common/common.runtime.properties"
load_config "druid.query.groupBy.bufferGrouperInitialBuckets" "${DRUID_QUERY_GROUPBY_BUFFERGROUPERINITIALBUCKETS:=0}" "_common/common.runtime.properties"
load_config "druid.query.groupBy.bufferGrouperMaxLoadFactor" "${DRUID_QUERY_GROUPBY_BUFFERGROUPERMAXLOADFACTOR:=0}" "_common/common.runtime.properties"
load_config "druid.query.groupBy.forceHashAggregation" "${DRUID_QUERY_GROUPBY_FORCEHASHAGGREGATION:=false}" "_common/common.runtime.properties"
load_config "druid.query.groupBy.intermediateCombineDegree" "${DRUID_QUERY_GROUPBY_INTERMEDIATECOMBINEDEGREE:=8}" "_common/common.runtime.properties"
load_config "druid.query.groupBy.numParallelCombineThreads" "${DRUID_QUERY_GROUPBY_NUMPARALLELCOMBINETHREADS:=1}" "_common/common.runtime.properties"
load_config "druid.query.groupBy.maxIntermediateRows" "${DRUID_QUERY_GROUPBY_MAXINTERMEDIATEROWS:=50000}" "_common/common.runtime.properties"
load_config "druid.query.groupBy.maxResults" "${DRUID_QUERY_GROUPBY_MAXRESULTS:=500000}" "_common/common.runtime.properties"
# ===========================================================================
load_config_with_opt "druid.host" "${DRUID_BROKER_HOSTNAME:=NULL}" "${DRUID_BROKER_HOSTNAME:=NULL}" "${HOSTNAME}" "broker/runtime.properties"
load_config "druid.bindOnHost" "${DRUID_BINDONHOST:=false}" "broker/runtime.properties"
load_config "druid.plaintextPort" "${DRUID_PLAINTEXTPORT:=8082}" "broker/runtime.properties"
load_config "druid.tlsPort" "${DRUID_TLSPORT:=8282}" "broker/runtime.properties"
load_config "druid.service" "druid/broker" "broker/runtime.properties"
load_config "druid.broker.balancery.type" "${DRUID_BROKER_BALANCERY_TYPE:=random}" "broker/runtime.properties"
load_config "druid.broker.select.tier" "${DRUID_BROKER_SELECT_TIER:=highestPriority}" "broker/runtime.properties"
load_config "druid.broker.select.tier.custom.priorities" "${DRUID_BROKER_SELECT_TIER_CUSTOM_PRIORITIES:=NULL}" "broker/runtime.properties"
load_config "druid.broker.http.numConnections" "${DRUID_BROKER_HTTP_NUMCONNECTIONS:=20}" "broker/runtime.properties"
load_config "druid.broker.http.compressionCodec" "${DRUID_BROKER_HTTP_COMPRESSIONCODEC:=gzip}" "broker/runtime.properties"
load_config "druid.broker.http.readTimeout" "${DRUID_BROKER_HTTP_READTIMEOUT:=PT15M}" "broker/runtime.properties"
load_config "druid.broker.http.unusedConnectionTimeout" "${DRUID_BROKER_HTTP_UNUSEDCONNECTIONTIMEOUT:=PT4M}" "broker/runtime.properties"
load_config "druid.broker.http.maxQueuedBytes" "${DRUID_BROKER_HTTP_MAXQUEUEDBYTES:=0}" "broker/runtime.properties"
load_config "druid.broker.http.numMaxThreads" "${DRUID_BROKER_HTTP_NUMMAXTHREADS:=NULL}" "broker/runtime.properties"
load_config "druid.broker.retryPolicy.numTries" "${DRUID_BROKER_RETRYPOLICY_NUMTRIES:=1}" "broker/runtime.properties"
load_config "druid.broker.cache.useCache" "${DRUID_BROKER_CACHE_USECACHE:=false}" "broker/runtime.properties"
load_config "druid.broker.cache.populateCache" "${DRUID_BROKER_CACHE_POPULATECACHE:=false}" "broker/runtime.properties"
load_config "druid.broker.cache.useResultLevelCache" "${DRUID_BROKER_CACHE_USERESULTLEVELCACHE:=false}" "broker/runtime.properties"
load_config "druid.broker.cache.populateResultLevelCache" "${DRUID_BROKER_CACHE_POPULATERESULTLEVELCACHE:=false}" "broker/runtime.properties"
load_config "druid.broker.cache.resultLevelCacheLimit" "${DRUID_BROKER_CACHE_RESULTLEVELCACHELIMIT:=NULL}" "broker/runtime.properties"
load_config "druid.broker.cache.unCacheable" "${DRUID_BROKER_CACHE_UNCACHEABLE:=NULL}" "broker/runtime.properties"
load_config "druid.broker.cache.cacheBulkMergeLimit" "${DRUID_BROKER_CACHE_CACHEBULKMERGELIMIT:=NULL}" "broker/runtime.properties"
load_config "druid.broker.cache.maxEntrySize" "${DRUID_BROKER_CACHE_MAXENTRYSIZE:=NULL}" "broker/runtime.properties"
load_config "druid.query.scheduler.numThreads" "${DRUID_QUERY_SCHEDULER_NUMTHREADS:=NULL}" "broker/runtime.properties"
load_config "druid.query.scheduler.laning.strategy" "${DRUID_QUERY_SCHEDULER_LANING_STRATEGY:=NULL}" "broker/runtime.properties"
load_config "druid.query.scheduler.laning.maxLowPercent" "${DRUID_QUERY_SCHEDULER_LANING_MAXLOWPERCENT:=NULL}" "broker/runtime.properties"
load_config "druid.query.scheduler.laning.isLimitPercent" "${DRUID_QUERY_SCHEDULER_LANING_ISLIMITPERCENT:=false}" "broker/runtime.properties"
load_config "druid.query.scheduler.prioritization.stategy" "${DRUID_QUERY_SCHEDULER_PRIORITIZATION_STATEGY:=manual}" "broker/runtime.properties"
load_config "druid.query.scheduler.prioritization.periodThreshold" "${DRUID_QUERY_SCHEDULER_PRIORITIZATION_PERIODTHRESHOLD:=NULL}" "broker/runtime.properties"
load_config "druid.query.scheduler.prioritization.durationThreshold" "${DRUID_QUERY_SCHEDULER_PRIORITIZATION_DURATIONTHRESHOLD:=NULL}" "broker/runtime.properties"
load_config "druid.query.scheduler.prioritization.segmentCountThreshold" "${DRUID_QUERY_SCHEDULER_PRIORITIZATION_SEGMENTCOUNTTHRESHOLD:=NULL}" "broker/runtime.properties"
load_config "druid.query.scheduler.prioritization.adjustment" "${DRUID_QUERY_SCHEDULER_PRIORITIZATION_ADJUSTMENT:=NULL}" "broker/runtime.properties"
load_config "druid.server.http.numThreads" "${DRUID_SERVER_HTTP_NUMTHREADS:=NULL}" "broker/runtime.properties"
load_config "druid.server.http.queueSize" "${DRUID_SERVER_HTTP_QUEUESIZE:=NULL}" "broker/runtime.properties"
load_config "druid.server.http.maxIdleTime" "${DRUID_SERVER_HTTP_MAXIDLETIME:=PT5M}" "broker/runtime.properties"
load_config "druid.server.http.enableRequestLimit" "${DRUID_SERVER_HTTP_ENABLEREQUESTLIMIT:=false}" "broker/runtime.properties"
load_config "druid.server.http.defaultQueryTimeout" "${DRUID_SERVER_HTTP_DEFAULTQUERYTIMEOUT:=300000}" "broker/runtime.properties"
load_config "druid.server.http.maxScatterGatherBytes" "${DRUID_SERVER_HTTP_MAXSCATTERGATHERBYTES:=NULL}" "broker/runtime.properties"
load_config "druid.server.http.maxSubqueryRows" "${DRUID_SERVER_HTTP_MAXSUBQUERYROWS:=100000}" "broker/runtime.properties"
load_config "druid.server.http.gracefulShutdownTimeout" "${DRUID_SERVER_HTTP_GRACEFULSHUTDOWNTIMEOUT:=PT0S}" "broker/runtime.properties"
load_config "druid.server.http.unannouncePropagationDelay" "${DRUID_SERVER_HTTP_UNANNOUNCEPROPAGATIONDELAY:=PT0S}" "broker/runtime.properties"
load_config "druid.server.http.maxQueryTimeout" "${DRUID_SERVER_HTTP_MAXQUERYTIMEOUT:=NULL}" "broker/runtime.properties"
load_config "druid.server.http.maxRequestHeaderSize" "${DRUID_SERVER_HTTP_MAXREQUESTHEADERSIZE:=NULL}" "broker/runtime.properties"
load_config "druid.processing.buffer.sizeBytes" "${DRUID_PROCESSING_BUFFER_SIZEBYTES:=NULL}" "broker/runtime.properties"
load_config "druid.processing.buffer.poolCacheMaxCount" "${DRUID_PROCESSING_BUFFER_POOLCACHEMAXCOUNT:=NULL}" "broker/runtime.properties"
load_config "druid.processing.formatString" "${DRUID_PROCESSING_FORMATSTRING:=processing-%s}" "broker/runtime.properties"
load_config "druid.processing.numMergeBuffers" "${DRUID_PROCESSING_NUMMERGEBUFFERS:=NULL}" "broker/runtime.properties"
load_config "druid.processing.numThreads" "${DRUID_PROCESSING_NUMTHREADS:=NULL}" "broker/runtime.properties"
load_config "druid.processing.columnCache.sizeBytes" "${DRUID_PROCESSING_COLUMNCACHE_SIZEBYTES:=0}" "broker/runtime.properties"
load_config "druid.processing.fifo" "${DRUID_PROCESSING_FIFO:=false}" "broker/runtime.properties"
load_config "druid.processing.tmpDir" "${DRUID_PROCESSING_TMPDIR:=NULL}" "broker/runtime.properties"
load_config "druid.processing.merge.useParallelMergePool" "${DRUID_PROCESSING_MERGE_USEPARALLELMERGEPOOL:=true}" "broker/runtime.properties"
load_config "druid.processing.merge.pool.parallelism" "${DRUID_PROCESSING_MERGE_POOL_PARALLELISM:=NULL}" "broker/runtime.properties"
load_config "druid.processing.merge.pool.defaultMaxQueryParallelism" "${DRUID_PROCESSING_MERGE_POOL_DEFAULTMAXQUERYPARALLELISM:=NULL}" "broker/runtime.properties"
load_config "druid.processing.merge.pool.awaitShutdownMillis" "${DRUID_PROCESSING_MERGE_POOL_AWAITSHUTDOWNMILLIS:=NULL}" "broker/runtime.properties"
load_config "druid.processing.merge.task.targetRunTimeMillis" "${DRUID_PROCESSING_MERGE_TASK_TARGETRUNTIMEMILLIS:=100}" "broker/runtime.properties"
load_config "druid.processing.merge.task.initialYieldNumRows" "${DRUID_PROCESSING_MERGE_TASK_INITIALYIELDNUMROWS:=16384}" "broker/runtime.properties"
load_config "druid.processing.merge.task.smallBatchNumRows" "${DRUID_PROCESSING_MERGE_TASK_SMALLBATCHNUMROWS:=4096}" "broker/runtime.properties"
load_config "druid.sql.enable" "${DRUID_SQL_ENABLE:=true}" "broker/runtime.properties"
load_config "druid.sql.avatica.enable" "${DRUID_SQL_AVATICA_ENABLE:=true}" "broker/runtime.properties"
load_config "druid.sql.avatica.maxConnections" "${DRUID_SQL_AVATICA_MAXCONNECTIONS:=25}" "broker/runtime.properties"
load_config "druid.sql.avatica.maxRowsPerFrame" "${DRUID_SQL_AVATICA_MAXROWSPERFRAME:=NULL}" "broker/runtime.properties"
load_config "druid.sql.avatica.maxStatementsPerConnection" "${DRUID_SQL_AVATICA_MAXSTATEMENTSPERCONNECTION:=4}" "broker/runtime.properties"
load_config "druid.sql.avatica.connectionIdleTimeout" "${DRUID_SQL_AVATICA_CONNECTIONIDLETIMEOUT:=PT5M}" "broker/runtime.properties"
load_config "druid.sql.http.enable" "${DRUID_SQL_HTTP_ENABLE:=true}" "broker/runtime.properties"
load_config "druid.sql.planner.maxTopNLimit" "${DRUID_SQL_PLANNER_MAXTOPNLIMIT:=100000}" "broker/runtime.properties"
load_config "druid.sql.planner.metadataRefreshPeriod" "${DRUID_SQL_PLANNER_METADATAREFRESHPERIOD:=PT1M}" "broker/runtime.properties"
load_config "druid.sql.planner.useApproximateCountDistinct" "${DRUID_SQL_PLANNER_USEAPPROXIMATECOUNTDISTINCT:=true}" "broker/runtime.properties"
load_config "druid.sql.planner.useApproximateTopN" "${DRUID_SQL_PLANNER_USEAPPROXIMATETOPN:=true}" "broker/runtime.properties"
load_config "druid.sql.planner.requireTimeCondition" "${DRUID_SQL_PLANNER_REQUIRETIMECONDITION:=false}" "broker/runtime.properties"
load_config "druid.sql.planner.sqlTimeZone" "${DRUID_SQL_PLANNER_SQLTIMEZONE:=UTC}" "broker/runtime.properties"
load_config "druid.sql.planner.metadataSegmentCacheEnable" "${DRUID_SQL_PLANNER_METADATASEGMENTCACHEENABLE:=false}" "broker/runtime.properties"
load_config "druid.sql.planner.metadataSegmentPollPeriod" "${DRUID_SQL_PLANNER_METADATASEGMENTPOLLPERIOD:=60000}" "broker/runtime.properties"
# ===========================================================================
load_config_with_opt "druid.host" "${DRUID_COORDINATOR_HOSTNAME:=NULL}" "${DRUID_COORDINATOR_HOSTNAME:=NULL}" "${HOSTNAME}" "coordinator/runtime.properties"
load_config "druid.bindOnHost" "${DRUID_BINDONHOST:=false}" "coordinator/runtime.properties"
load_config "druid.plaintextPort" "${DRUID_PLAINTEXTPORT:=8081}" "coordinator/runtime.properties"
load_config "druid.tlsPort" "${DRUID_TLSPORT:=8281}" "coordinator/runtime.properties"
load_config "druid.service" "druid/coordinator" "coordinator/runtime.properties"
load_config "druid.coordinator.period" "${DRUID_COORDINATOR_PERIOD:=PT60S}" "coordinator/runtime.properties"
load_config "druid.coordinator.period.indexingPeriod" "${DRUID_COORDINATOR_PERIOD_INDEXINGPERIOD:=PT1800S}" "coordinator/runtime.properties"
load_config "druid.coordinator.startDelay" "${DRUID_COORDINATOR_STARTDELAY:=PT300S}" "coordinator/runtime.properties"
load_config "druid.coordinator.load.timeout" "${DRUID_COORDINATOR_LOAD_TIMEOUT:=PT15M}" "coordinator/runtime.properties"
load_config "druid.coordinator.kill.pendingSegments.on" "${DRUID_COORDINATOR_KILL_PENDINGSEGMENTS_ON:=true}" "coordinator/runtime.properties"
load_config "druid.coordinator.kill.on" "${DRUID_COORDINATOR_KILL_ON:=false}" "coordinator/runtime.properties"
load_config "druid.coordinator.kill.period" "${DRUID_COORDINATOR_KILL_PERIOD:=P1D}" "coordinator/runtime.properties"
load_config "druid.coordinator.kill.durationToRetain" "${DRUID_COORDINATOR_KILL_DURATIONTORETAIN:=PT-1S}" "coordinator/runtime.properties"
load_config "druid.coordinator.kill.maxSegments" "${DRUID_COORDINATOR_KILL_MAXSEGMENTS:=0}" "coordinator/runtime.properties"
load_config "druid.coordinator.balancer.strategy" "${DRUID_COORDINATOR_BALANCER_STRATEGY:=cost}" "coordinator/runtime.properties"
load_config "druid.coordinator.balancer.cachingCost.awaitInitialization" "${DRUID_COORDINATOR_BALANCER_CACHINGCOST_AWAITINITIALIZATION:=false}" "coordinator/runtime.properties"
load_config "druid.coordinator.loadqueuepeon.type" "${DRUID_COORDINATOR_LOADQUEUEPEON_TYPE:=curator}" "coordinator/runtime.properties"
load_config "druid.coordinator.loadqueuepeon.repeatDelay" "${DRUID_COORDINATOR_LOADQUEUEPEON_REPEATDELAY:=PT0.050S}" "coordinator/runtime.properties"
load_config "druid.coordinator.loadqueuepeon.http.batchSize" "${DRUID_COORDINATOR_LOADQUEUEPEON_HTTP_BATCHSIZE:=1}" "coordinator/runtime.properties"
load_config "druid.coordinator.asOverlord.enabled" "${DRUID_COORDINATOR_ASOVERLORD_ENABLED:=false}" "coordinator/runtime.properties"
load_config "druid.coordinator.asOverlord.overlordService" "${DRUID_COORDINATOR_ASOVERLORD_OVERLORDSERVICE:=NULL}" "coordinator/runtime.properties"
load_config "druid.coordinator.segment.awaitInitializationOnStart" "${DRUID_COORDINATOR_SEGMENT_AWAITINITIALIZATIONONSTART:=true}" "coordinator/runtime.properties"
load_config "druid.serverview.type" "${DRUID_SERVERVIEW_TYPE:=batch}" "coordinator/runtime.properties"
load_config "druid.manager.config.pollDuration" "${DRUID_MANAGER_CONFIG_POLLDURATION:=PT1M}" "coordinator/runtime.properties"
load_config "druid.manager.segments.pollDuration" "${DRUID_MANAGER_SEGMENTS_POLLDURATION:=PT1M}" "coordinator/runtime.properties"
load_config "druid.manager.rules.pollDuration" "${DRUID_MANAGER_RULES_POLLDURATION:=PT1M}" "coordinator/runtime.properties"
load_config "druid.manager.rules.defaultRule" "${DRUID_MANAGER_RULES_DEFAULTRULE:=_default}" "coordinator/runtime.properties"
load_config "druid.manager.rules.alertThreshold" "${DRUID_MANAGER_RULES_ALERTTHRESHOLD:=PT10M}" "coordinator/runtime.properties"
load_config "druid.manager.lookups.hostDeleteTimeout" "${DRUID_MANAGER_LOOKUPS_HOSTDELETETIMEOUT:=PT1S}" "coordinator/runtime.properties"
load_config "druid.manager.lookups.hostUpdateTimeout" "${DRUID_MANAGER_LOOKUPS_HOSTUPDATETIMEOUT:=PT10S}" "coordinator/runtime.properties"
load_config "druid.manager.lookups.deleteAllTimeout" "${DRUID_MANAGER_LOOKUPS_DELETEALLTIMEOUT:=PT10S}" "coordinator/runtime.properties"
load_config "druid.manager.lookups.updateAllTimeout" "${DRUID_MANAGER_LOOKUPS_UPDATEALLTIMEOUT:=PT60S}" "coordinator/runtime.properties"
load_config "druid.manager.lookups.threadPoolSize" "${DRUID_MANAGER_LOOKUPS_THREADPOOLSIZE:=10}" "coordinator/runtime.properties"
load_config "druid.manager.lookups.period" "${DRUID_MANAGER_LOOKUPS_PERIOD:=NULL}" "coordinator/runtime.properties"
# ===========================================================================
load_config_with_opt "druid.host" "${DRUID_HISTORICAL_HOSTNAME:=NULL}" "${DRUID_HISTORICAL_HOSTNAME:=NULL}" "${HOSTNAME}" "historical/runtime.properties"
load_config "druid.bindOnHost" "${DRUID_BINDONHOST:=false}" "historical/runtime.properties"
load_config "druid.plaintextPort" "${DRUID_PLAINTEXTPORT:=8083}" "historical/runtime.properties"
load_config "druid.tlsPort" "${DRUID_TLSPORT:=8283}" "historical/runtime.properties"
load_config "druid.service" "druid/historical" "historical/runtime.properties"
load_config "druid.server.maxSize" "${DRUID_SERVER_MAXSIZE:=NULL}" "historical/runtime.properties"
load_config "druid.server.tier" "${DRUID_SERVER_TIER:=_default_tier}" "historical/runtime.properties"
load_config "druid.server.priority" "${DRUID_SERVER_PRIORITY:=0}" "historical/runtime.properties"
load_config "druid.server.http.numThreads" "${DRUID_SERVER_HTTP_NUMTHREADS:=NULL}" "historical/runtime.properties"
load_config "druid.server.http.queueSize" "${DRUID_SERVER_HTTP_QUEUESIZE:=NULL}" "historical/runtime.properties"
load_config "druid.server.http.maxIdleTime" "${DRUID_SERVER_HTTP_MAXIDLETIME:=PT5M}" "historical/runtime.properties"
load_config "druid.server.http.enableRequestLimit" "${DRUID_SERVER_HTTP_ENABLEREQUESTLIMIT:=false}" "historical/runtime.properties"
load_config "druid.server.http.defaultQueryTimeout" "${DRUID_SERVER_HTTP_DEFAULTQUERYTIMEOUT:=300000}" "historical/runtime.properties"
load_config "druid.server.http.gracefulShutdownTimeout" "${DRUID_SERVER_HTTP_GRACEFULSHUTDOWNTIMEOUT:=PT0S}" "historical/runtime.properties"
load_config "druid.server.http.unannouncePropagationDelay" "${DRUID_SERVER_HTTP_UNANNOUNCEPROPAGATIONDELAY:=PT0S}" "historical/runtime.properties"
load_config "druid.server.http.maxQueryTimeout" "${DRUID_SERVER_HTTP_MAXQUERYTIMEOUT:=NULL}" "historical/runtime.properties"
load_config "druid.server.http.maxRequestHeaderSize" "${DRUID_SERVER_HTTP_MAXREQUESTHEADERSIZE:=NULL}" "historical/runtime.properties"
load_config "druid.segmentCache.locations" "${DRUID_SEGMENTCACHE_LOCATIONS:=[{\"path\":\"/mnt/druidSegments\",\"maxSize\":\"10k\",\"freeSpacePercent\":1.0\}]}" "historical/runtime.properties"
load_config "druid.segmentCache.locationSelectorStrategy" "${DRUID_SEGMENTCACHE_LOCATIONSELECTORSTRATEGY:=NULL}" "historical/runtime.properties"
load_config "druid.segmentCache.deleteOnRemove" "${DRUID_SEGMENTCACHE_DELETEONREMOVE:=true}" "historical/runtime.properties"
load_config "druid.segmentCache.dropSegmentDelayMillis" "${DRUID_SEGMENTCACHE_DROPSEGMENTDELAYMILLIS:=30000}" "historical/runtime.properties"
load_config "druid.segmentCache.infoDir" "${DRUID_HOME}/info_dir" "historical/runtime.properties"
load_config "druid.segmentCache.announceIntervalMillis" "${DRUID_SEGMENTCACHE_ANNOUNCEINTERVALMILLIS:=5000}" "historical/runtime.properties"
load_config "druid.segmentCache.numLoadingThreads" "${DRUID_SEGMENTCACHE_NUMLOADINGTHREADS:=NULL}" "historical/runtime.properties"
load_config "druid.segmentCache.numBootstrapThreads" "${DRUID_SEGMENTCACHE_NUMBOOTSTRAPTHREADS:=NULL}" "historical/runtime.properties"
load_config "druid.segmentCache.lazyLoadOnStart" "${DRUID_SEGMENTCACHE_LAZYLOADONSTART:=false}" "historical/runtime.properties"
load_config "druid.coordinator.loadqueuepeon.curator.numCallbackThreads" "${DRUID_COORDINATOR_LOADQUEUEPEON_CURATOR_NUMCALLBACKTHREADS:=2}" "historical/runtime.properties"
load_config "druid.processing.buffer.sizeBytes" "${DRUID_PROCESSING_BUFFER_SIZEBYTES:=NULL}" "historical/runtime.properties"
load_config "druid.processing.buffer.poolCacheMaxCount" "${DRUID_PROCESSING_BUFFER_POOLCACHEMAXCOUNT:=NULL}" "historical/runtime.properties"
load_config "druid.processing.formatString" "${DRUID_PROCESSING_FORMATSTRING:=processing-%s}" "historical/runtime.properties"
load_config "druid.processing.numMergeBuffers" "${DRUID_PROCESSING_NUMMERGEBUFFERS:=NULL}" "historical/runtime.properties"
load_config "druid.processing.numThreads" "${DRUID_PROCESSING_NUMTHREADS:=NULL}" "historical/runtime.properties"
load_config "druid.processing.columnCache.sizeBytes" "${DRUID_PROCESSING_COLUMNCACHE_SIZEBYTES:=0}" "historical/runtime.properties"
load_config "druid.processing.fifo" "${DRUID_PROCESSING_FIFO:=false}" "historical/runtime.properties"
load_config "druid.processing.tmpDir" "${DRUID_PROCESSING_TMPDIR:=NULL}" "historical/runtime.properties"
load_config "druid.historical.cache.useCache" "${DRUID_HISTORICAL_CACHE_USECACHE:=false}" "historical/runtime.properties"
load_config "druid.historical.cache.populateCache" "${DRUID_HISTORICAL_CACHE_POPULATECACHE:=false}" "historical/runtime.properties"
load_config "druid.historical.cache.unCacheable" "${DRUID_HISTORICAL_CACHE_UNCACHEABLE:=[]}" "historical/runtime.properties"
load_config "druid.historical.cache.maxEntrySize" "${DRUID_HISTORICAL_CACHE_MAXENTRYSIZE:=NULL}" "historical/runtime.properties"
# ===========================================================================
load_config_with_opt "druid.host" "${DRUID_MIDDLEMANAGER_HOSTNAME:=NULL}" "${DRUID_MIDDLEMANAGER_HOSTNAME:=NULL}" "${HOSTNAME}" "middleManager/runtime.properties"
load_config "druid.bindOnHost" "${DRUID_BINDONHOST:=false}" "middleManager/runtime.properties"
load_config "druid.plaintextPort" "${DRUID_PLAINTEXTPORT:=8091}" "middleManager/runtime.properties"
load_config "druid.tlsPort" "${DRUID_TLSPORT:=8291}" "middleManager/runtime.properties"
load_config "druid.service" "druid/middlemanager" "middleManager/runtime.properties"
load_config "druid.indexer.runner.allowedPrefixes" "${DRUID_INDEXER_RUNNER_ALLOWEDPREFIXES:=[\"com.metamx\",\"druid\",\"org.apache.druid\",\"user.timezone\",\"file.encoding\",\"java.io.tmpdir\",\"hadoop\"]}" "middleManager/runtime.properties"
load_config "druid.indexer.runner.compressZnodes" "${DRUID_INDEXER_RUNNER_COMPRESSZNODES:=true}" "middleManager/runtime.properties"
load_config "druid.indexer.runner.classpath" "${DRUID_INDEXER_RUNNER_CLASSPATH:=NULL}" "middleManager/runtime.properties"
load_config "druid.indexer.runner.javaCommand" "${DRUID_INDEXER_RUNNER_JAVACOMMAND:=java}" "middleManager/runtime.properties"
load_config "druid.indexer.runner.javaOptsArray" "${DRUID_INDEXER_RUNNER_JAVAOPTSARRAY:=[]}" "middleManager/runtime.properties"
load_config "druid.indexer.runner.maxZnodeBytes" "${DRUID_INDEXER_RUNNER_MAXZNODEBYTES:=524288}" "middleManager/runtime.properties"
load_config "druid.indexer.runner.startPort" "${DRUID_INDEXER_RUNNER_STARTPORT:=8100}" "middleManager/runtime.properties"
load_config "druid.indexer.runner.endPort" "${DRUID_INDEXER_RUNNER_ENDPORT:=65535}" "middleManager/runtime.properties"
load_config "druid.indexer.runner.ports" "${DRUID_INDEXER_RUNNER_PORTS:=[]}" "middleManager/runtime.properties"
load_config "druid.indexer.task.baseDir" "${DRUID_INDEXER_TASK_BASEDIR:=NULL}" "middleManager/runtime.properties"
load_config "druid.indexer.task.baseTaskDir" "${DRUID_INDEXER_TASK_BASETASKDIR:=NULL}" "middleManager/runtime.properties"
load_config "druid.indexer.task.defaultHadoopCoordinates" "${DRUID_INDEXER_TASK_DEFAULTHADOOPCOORDINATES:=[\"org.apache.hadoop:hadoop-client:2.8.5\"]}" "middleManager/runtime.properties"
load_config "druid.indexer.task.defaultRowFlushBoundary" "${DRUID_INDEXER_TASK_DEFAULTROWFLUSHBOUNDARY:=75000}" "middleManager/runtime.properties"
load_config "druid.indexer.task.directoryLockTimeout" "${DRUID_INDEXER_TASK_DIRECTORYLOCKTIMEOUT:=PT10M}" "middleManager/runtime.properties"
load_config "druid.indexer.task.gracefulShutdownTimeout" "${DRUID_INDEXER_TASK_GRACEFULSHUTDOWNTIMEOUT:=PT5M}" "middleManager/runtime.properties"
load_config "druid.indexer.task.hadoopWorkingPath" "${DRUID_INDEXER_TASK_HADOOPWORKINGPATH:=/tmp/druid-indexing}" "middleManager/runtime.properties"
load_config "druid.indexer.task.restoreTasksOnRestart" "${DRUID_INDEXER_TASK_RESTORETASKSONRESTART:=false}" "middleManager/runtime.properties"
load_config "druid.indexer.server.maxChatRequests" "${DRUID_INDEXER_SERVER_MAXCHATREQUESTS:=0}" "middleManager/runtime.properties"
load_config "druid.worker.ip" "${DRUID_WORKER_IP:=localhost}" "middleManager/runtime.properties"
load_config "druid.worker.version" "${DRUID_WORKER_VERSION:=0}" "middleManager/runtime.properties"
load_config "druid.worker.capacity" "${DRUID_WORKER_CAPACITY:=NULL}" "middleManager/runtime.properties"
load_config "druid.worker.category" "${DRUID_WORKER_CATEGORY:=__default_worker_category}" "middleManager/runtime.properties"
load_config "druid.processing.buffer.sizeBytes" "${DRUID_PROCESSING_BUFFER_SIZEBYTES:=NULL}" "middleManager/runtime.properties"
load_config "druid.processing.buffer.poolCacheMaxCount" "${DRUID_PROCESSING_BUFFER_POOLCACHEMAXCOUNT:=NULL}" "middleManager/runtime.properties"
load_config "druid.processing.formatString" "${DRUID_PROCESSING_FORMATSTRING:=processing-%s}" "middleManager/runtime.properties"
load_config "druid.processing.numMergeBuffers" "${DRUID_PROCESSING_NUMMERGEBUFFERS:=NULL}" "middleManager/runtime.properties"
load_config "druid.processing.numThreads" "${DRUID_PROCESSING_NUMTHREADS:=NULL}" "middleManager/runtime.properties"
load_config "druid.processing.columnCache.sizeBytes" "${DRUID_PROCESSING_COLUMNCACHE_SIZEBYTES:=0}" "middleManager/runtime.properties"
load_config "druid.processing.fifo" "${DRUID_PROCESSING_FIFO:=false}" "middleManager/runtime.properties"
load_config "druid.processing.tmpDir" "${DRUID_PROCESSING_TMPDIR:=NULL}" "middleManager/runtime.properties"
load_config "druid.realtime.cache.useCache" "${DRUID_REALTIME_CACHE_USECACHE:=false}" "middleManager/runtime.properties"
load_config "druid.realtime.cache.populateCache" "${DRUID_REALTIME_CACHE_POPULATECACHE:=false}" "middleManager/runtime.properties"
load_config "druid.realtime.cache.unCacheable" "${DRUID_REALTIME_CACHE_UNCACHEABLE:=[]}" "middleManager/runtime.properties"
load_config "druid.realtime.cache.maxEntrySize" "${DRUID_REALTIME_CACHE_MAXENTRYSIZE:=NULL}" "middleManager/runtime.properties"
load_config "druid.peon.mode" "${DRUID_PEON_MODE:=remote}" "middleManager/runtime.properties"
load_config "druid.peon.taskActionClient.retry.minWait" "${DRUID_PEON_TASKACTIONCLIENT_RETRY_MINWAIT:=PT5S}" "middleManager/runtime.properties"
load_config "druid.peon.taskActionClient.retry.maxWait" "${DRUID_PEON_TASKACTIONCLIENT_RETRY_MAXWAIT:=PT1M}" "middleManager/runtime.properties"
load_config "druid.peon.taskActionClient.retry.maxRetryCount" "${DRUID_PEON_TASKACTIONCLIENT_RETRY_MAXRETRYCOUNT:=60}" "middleManager/runtime.properties"
load_config "druid.peon.defaultSegmentWriteOutMediumFactory.type" "${DRUID_PEON_DEFAULTSEGMENTWRITEOUTMEDIUMFACTORY_TYPE:=tmpFile}" "middleManager/runtime.properties"
# ===========================================================================
load_config_with_opt "druid.host" "${DRUID_OVERLORD_HOSTNAME:=NULL}" "${DRUID_OVERLORD_HOSTNAME:=NULL}" "${HOSTNAME}" "overlord/runtime.properties"
load_config "druid.bindOnHost" "${DRUID_BINDONHOST:=false}" "overlord/runtime.properties"
load_config "druid.plaintextPort" "${DRUID_PLAINTEXTPORT:=8090}" "overlord/runtime.properties"
load_config "druid.tlsPort" "${DRUID_TLSPORT:=8290}" "overlord/runtime.properties"
load_config "druid.service" "druid/overlord" "overlord/runtime.properties"
load_config "druid.indexer.runner.type" "${DRUID_INDEXER_RUNNER_TYPE:=local}" "overlord/runtime.properties"
load_config "druid.indexer.storage.type" "${DRUID_INDEXER_STORAGE_TYPE:=local}" "overlord/runtime.properties"
load_config "druid.indexer.storage.recentlyFinishedThreshold" "${DRUID_INDEXER_STORAGE_RECENTLYFINISHEDTHRESHOLD:=PT24H}" "overlord/runtime.properties"
load_config "druid.indexer.tasklock.forceTimeChunkLock" "${DRUID_INDEXER_TASKLOCK_FORCETIMECHUNKLOCK:=true}" "overlord/runtime.properties"
load_config "druid.indexer.queue.maxSize" "${DRUID_INDEXER_QUEUE_MAXSIZE:=NULL}" "overlord/runtime.properties"
load_config "druid.indexer.queue.startDelay" "${DRUID_INDEXER_QUEUE_STARTDELAY:=PT1M}" "overlord/runtime.properties"
load_config "druid.indexer.queue.restartDelay" "${DRUID_INDEXER_QUEUE_RESTARTDELAY:=PT30S}" "overlord/runtime.properties"
load_config "druid.indexer.queue.storageSyncRate" "${DRUID_INDEXER_QUEUE_STORAGESYNCRATE:=PT1M}" "overlord/runtime.properties"
load_config "druid.indexer.runner.taskAssignmentTimeout" "${DRUID_INDEXER_RUNNER_TASKASSIGNMENTTIMEOUT:=PT5M}" "overlord/runtime.properties"
load_config "druid.indexer.runner.minWorkerVersion" "${DRUID_INDEXER_RUNNER_MINWORKERVERSION:=0}" "overlord/runtime.properties"
load_config "druid.indexer.runner.compressZnodes" "${DRUID_INDEXER_RUNNER_COMPRESSZNODES:=true}" "overlord/runtime.properties"
load_config "druid.indexer.runner.maxZnodeBytes" "${DRUID_INDEXER_RUNNER_MAXZNODEBYTES:=NULL}" "overlord/runtime.properties"
load_config "druid.indexer.runner.taskCleanupTimeout" "${DRUID_INDEXER_RUNNER_TASKCLEANUPTIMEOUT:=PT15M}" "overlord/runtime.properties"
load_config "druid.indexer.runner.taskShutdownLinkTimeout" "${DRUID_INDEXER_RUNNER_TASKSHUTDOWNLINKTIMEOUT:=PT1M}" "overlord/runtime.properties"
load_config "druid.indexer.runner.pendingTasksRunnerNumThreads" "${DRUID_INDEXER_RUNNER_PENDINGTASKSRUNNERNUMTHREADS:=1}" "overlord/runtime.properties"
load_config "druid.indexer.runner.maxRetriesBeforeBlacklist" "${DRUID_INDEXER_RUNNER_MAXRETRIESBEFOREBLACKLIST:=5}" "overlord/runtime.properties"
load_config "druid.indexer.runner.workerBlackListBackoffTime" "${DRUID_INDEXER_RUNNER_WORKERBLACKLISTBACKOFFTIME:=PT15M}" "overlord/runtime.properties"
load_config "druid.indexer.runner.workerBlackListCleanupPeriod" "${DRUID_INDEXER_RUNNER_WORKERBLACKLISTCLEANUPPERIOD:=PT5M}" "overlord/runtime.properties"
load_config "druid.indexer.runner.maxPercentageBlacklistWorkers" "${DRUID_INDEXER_RUNNER_MAXPERCENTAGEBLACKLISTWORKERS:=20}" "overlord/runtime.properties"
load_config "druid.indexer.autoscale.strategy" "${DRUID_INDEXER_AUTOSCALE_STRATEGY:=noop}" "overlord/runtime.properties"
load_config "druid.indexer.autoscale.doAutoscale" "${DRUID_INDEXER_AUTOSCALE_DOAUTOSCALE:=false}" "overlord/runtime.properties"
load_config "druid.indexer.autoscale.provisionPeriod" "${DRUID_INDEXER_AUTOSCALE_PROVISIONPERIOD:=PT1M}" "overlord/runtime.properties"
load_config "druid.indexer.autoscale.terminatePeriod" "${DRUID_INDEXER_AUTOSCALE_TERMINATEPERIOD:=PT5M}" "overlord/runtime.properties"
load_config "druid.indexer.autoscale.originTime" "${DRUID_INDEXER_AUTOSCALE_ORIGINTIME:=2012-01-01T00:55:00.000Z}" "overlord/runtime.properties"
load_config "druid.indexer.autoscale.workerIdleTimeout" "${DRUID_INDEXER_AUTOSCALE_WORKERIDLETIMEOUT:=PT90M}" "overlord/runtime.properties"
load_config "druid.indexer.autoscale.maxScalingDuration" "${DRUID_INDEXER_AUTOSCALE_MAXSCALINGDURATION:=PT15M}" "overlord/runtime.properties"
load_config "druid.indexer.autoscale.numEventsToTrack" "${DRUID_INDEXER_AUTOSCALE_NUMEVENTSTOTRACK:=10}" "overlord/runtime.properties"
load_config "druid.indexer.autoscale.pendingTaskTimeout" "${DRUID_INDEXER_AUTOSCALE_PENDINGTASKTIMEOUT:=PT30S}" "overlord/runtime.properties"
load_config "druid.indexer.autoscale.workerVersion" "${DRUID_INDEXER_AUTOSCALE_WORKERVERSION:=NULL}" "overlord/runtime.properties"
load_config "druid.indexer.autoscale.workerPort" "${DRUID_INDEXER_AUTOSCALE_WORKERPORT:=8080}" "overlord/runtime.properties"
load_config "druid.supervisor.healthinessThreshold" "${DRUID_SUPERVISOR_HEALTHINESSTHRESHOLD:=3}" "overlord/runtime.properties"
load_config "druid.supervisor.unhealthinessThreshold" "${DRUID_SUPERVISOR_UNHEALTHINESSTHRESHOLD:=3}" "overlord/runtime.properties"
load_config "druid.supervisor.taskHealthinessThreshold" "${DRUID_SUPERVISOR_TASKHEALTHINESSTHRESHOLD:=3}" "overlord/runtime.properties"
load_config "druid.supervisor.taskUnhealthinessThreshold" "${DRUID_SUPERVISOR_TASKUNHEALTHINESSTHRESHOLD:=3}" "overlord/runtime.properties"
load_config "druid.supervisor.storeStackTrace" "${DRUID_SUPERVISOR_STORESTACKTRACE:=false}" "overlord/runtime.properties"
load_config "druid.supervisor.maxStoreExceptionEvents" "${DRUID_SUPERVISOR_MAXSTOREEXCEPTIONEVENTS:=NULL}" "overlord/runtime.properties"
# ===========================================================================
load_config_with_opt "druid.host" "${DRUID_ROUTER_HOSTNAME:=NULL}" "${DRUID_ROUTER_HOSTNAME:=NULL}" "${HOSTNAME}" "router/runtime.properties"
load_config "druid.bindOnHost" "${DRUID_BINDONHOST:=false}" "router/runtime.properties"
load_config "druid.plaintextPort" "${DRUID_PLAINTEXTPORT:=8888}" "router/runtime.properties"
load_config "druid.tlsPort" "${DRUID_TLSPORT:=9088}" "router/runtime.properties"
load_config "druid.service" "druid/router" "router/runtime.properties"
load_config "druid.router.defaultBrokerServiceName" "${DRUID_ROUTER_DEFAULTBROKERSERVICENAME:=druid/broker}" "router/runtime.properties"
load_config "druid.router.tierToBrokerMap" "${DRUID_ROUTER_TIERTOBROKERMAP:={\"_default_tier\":\"\"\}}" "router/runtime.properties"
load_config "druid.router.defaultRule" "${DRUID_ROUTER_DEFAULTRULE:=_default}" "router/runtime.properties"
load_config "druid.router.pollPeriod" "${DRUID_ROUTER_POLLPERIOD:=PT1M}" "router/runtime.properties"
load_config "druid.router.strategies" "${DRUID_ROUTER_STRATEGIES:=[{\"type\":\"timeBoundary\"\},{\"type\":\"priority\"\}]}" "router/runtime.properties"
load_config "druid.router.avatica.balancer.type" "${DRUID_ROUTER_AVATICA_BALANCER_TYPE:=rendezvousHash}" "router/runtime.properties"
load_config "druid.router.managementProxy.enabled" "${DRUID_ROUTER_MANAGEMENTPROXY_ENABLED:=false}" "router/runtime.properties"
load_config "druid.router.http.numConnections" "${DRUID_ROUTER_HTTP_NUMCONNECTIONS:=20}" "router/runtime.properties"
load_config "druid.router.http.readTimeout" "${DRUID_ROUTER_HTTP_READTIMEOUT:=PT15M}" "router/runtime.properties"
load_config "druid.router.http.numMaxThreads" "${DRUID_ROUTER_HTTP_NUMMAXTHREADS:=NULL}" "router/runtime.properties"
load_config "druid.router.http.numRequestsQueued" "${DRUID_ROUTER_HTTP_NUMREQUESTSQUEUED:=1024}" "router/runtime.properties"
load_config "druid.router.http.requestBuffersize" "${DRUID_ROUTER_HTTP_REQUESTBUFFERSIZE:=NULL}" "router/runtime.properties"
# ===========================================================================
